// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Current user from JWT",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.AuthMeResponse"
                        }
                    }
                }
            }
        },
        "/auth/miniapp": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Mini-app login (exchange launch token for JWT)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.AuthMiniappResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/verify": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verify phone, get launch token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.AuthVerifyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/chat-links": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChatLinks"
                ],
                "summary": "Chat links for a dormitory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dormitory UUID",
                        "name": "dormitory_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ChatLinkListResponse"
                        }
                    }
                }
            }
        },
        "/cleaning/exemptions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cleaning"
                ],
                "summary": "Cleaning duty exemptions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dormitory UUID",
                        "name": "dormitory_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CleaningExemptionResponse"
                        }
                    }
                }
            }
        },
        "/cleaning/penalties": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cleaning"
                ],
                "summary": "Penalty cleaning duties",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dormitory UUID",
                        "name": "dormitory_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CleaningPenaltyResponse"
                        }
                    }
                }
            }
        },
        "/cleaning/schedule": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cleaning"
                ],
                "summary": "Cleaning schedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dormitory UUID",
                        "name": "dormitory_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Month 1-12",
                        "name": "month",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Year",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CleaningScheduleResponse"
                        }
                    }
                }
            }
        },
        "/dormitories": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dormitories"
                ],
                "summary": "List all active dormitories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.DormitoryListResponse"
                        }
                    }
                }
            }
        },
        "/dormitories/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dormitories"
                ],
                "summary": "Get dormitory by UUID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dormitory UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.DormitoryItem"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dormitories/{id}/floors": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dormitories"
                ],
                "summary": "Floors of a dormitory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dormitory UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.FloorListResponse"
                        }
                    }
                }
            }
        },
        "/dormitories/{id}/staff": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dormitories"
                ],
                "summary": "Staff of a dormitory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dormitory UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StaffListResponse"
                        }
                    }
                }
            }
        },
        "/employees/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employees"
                ],
                "summary": "Employee profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.EmployeeInfoResponse"
                        }
                    }
                }
            }
        },
        "/employees/{id}/dormitories": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employees"
                ],
                "summary": "Employee's assigned dormitories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.EmployeeDormitoriesResponse"
                        }
                    }
                }
            }
        },
        "/floors/{id}/rooms": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Rooms on a floor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Floor UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RoomListResponse"
                        }
                    }
                }
            }
        },
        "/laundry/bookings": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Laundry"
                ],
                "summary": "Book a laundry slot",
                "parameters": [
                    {
                        "description": "Booking",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "date": {
                                    "type": "string"
                                },
                                "machine_id": {
                                    "type": "string"
                                },
                                "slot_end": {
                                    "type": "string"
                                },
                                "slot_start": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.LaundryBookingResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/laundry/bookings/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Laundry"
                ],
                "summary": "Cancel laundry booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Booking UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.MessageResponse"
                        }
                    }
                }
            }
        },
        "/laundry/machines": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Laundry"
                ],
                "summary": "Washing machines in a dormitory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dormitory UUID",
                        "name": "dormitory_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.WashingMachineListResponse"
                        }
                    }
                }
            }
        },
        "/laundry/settings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Laundry"
                ],
                "summary": "Laundry settings for a dormitory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dormitory UUID",
                        "name": "dormitory_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.LaundrySettingsResponse"
                        }
                    }
                }
            }
        },
        "/laundry/slots": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Laundry"
                ],
                "summary": "Available laundry time slots",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dormitory UUID",
                        "name": "dormitory_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date YYYY-MM-DD",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.LaundrySlotListResponse"
                        }
                    }
                }
            }
        },
        "/reference-materials": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "References"
                ],
                "summary": "Reference materials for a dormitory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dormitory UUID",
                        "name": "dormitory_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReferenceMaterialListResponse"
                        }
                    }
                }
            }
        },
        "/residents/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Residents"
                ],
                "summary": "Resident profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resident UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResidentProfileResponse"
                        }
                    }
                }
            }
        },
        "/residents/{id}/debt": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Residents"
                ],
                "summary": "Resident financial debt",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resident UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResidentDebtResponse"
                        }
                    }
                }
            }
        },
        "/roles": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "All system and custom roles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RoleListResponse"
                        }
                    }
                }
            }
        },
        "/rooms/search": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Search rooms by number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room number substring",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RoomListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/rooms/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Get room by UUID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RoomItem"
                        }
                    }
                }
            }
        },
        "/rooms/{id}/items": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Room material items",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.MaterialItemListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Add material item to room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Item data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "condition": {
                                    "type": "string"
                                },
                                "inventory_number": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                },
                                "quantity": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.MaterialItemResponse"
                        }
                    }
                }
            }
        },
        "/rooms/{id}/residents": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Residents of a room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RoomResidentsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AuthMeResponse": {
            "type": "object",
            "properties": {
                "contract_end_date": {
                    "type": "string"
                },
                "contract_number": {
                    "type": "string"
                },
                "contract_start_date": {
                    "type": "string"
                },
                "dormitory": {
                    "type": "string",
                    "example": "Общежитие №8"
                },
                "first_name": {
                    "type": "string",
                    "example": "Артём"
                },
                "last_name": {
                    "type": "string"
                },
                "middle_name": {
                    "type": "string"
                },
                "person_type": {
                    "type": "string",
                    "example": "student"
                },
                "room_number": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string",
                    "example": "abc6efcd-487b-4b42-a30c-3dbb0a60cfdd"
                }
            }
        },
        "api.AuthMiniUser": {
            "type": "object",
            "properties": {
                "person_type": {
                    "type": "string",
                    "example": "student"
                },
                "user_id": {
                    "type": "string",
                    "example": "abc6efcd-487b-4b42-a30c-3dbb0a60cfdd"
                }
            }
        },
        "api.AuthMiniappResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbG..."
                },
                "user": {
                    "$ref": "#/definitions/api.AuthMiniUser"
                }
            }
        },
        "api.AuthUser": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string",
                    "example": "Артём"
                },
                "person_type": {
                    "type": "string",
                    "example": "student"
                },
                "phone": {
                    "type": "string",
                    "example": "79001234501"
                },
                "user_id": {
                    "type": "string",
                    "example": "abc6efcd-487b-4b42-a30c-3dbb0a60cfdd"
                }
            }
        },
        "api.AuthVerifyResponse": {
            "type": "object",
            "properties": {
                "launch_token": {
                    "type": "string",
                    "example": "abc-uuid-token"
                },
                "user": {
                    "$ref": "#/definitions/api.AuthUser"
                }
            }
        },
        "api.ChatLinkItem": {
            "type": "object",
            "properties": {
                "dormitory_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000000001"
                },
                "floor_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000010001"
                },
                "id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000500001"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "link_type": {
                    "type": "string",
                    "example": "dormitory"
                },
                "platform": {
                    "type": "string",
                    "example": "telegram"
                },
                "title": {
                    "type": "string",
                    "example": "Чат общежития №8"
                },
                "url": {
                    "type": "string",
                    "example": "https://t.me/dorm8_mock"
                }
            }
        },
        "api.ChatLinkListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ChatLinkItem"
                    }
                }
            }
        },
        "api.CleaningDuty": {
            "type": "object",
            "properties": {
                "dormitory_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000000001"
                },
                "duty_date": {
                    "type": "string",
                    "example": "2026-08-15"
                },
                "id": {
                    "type": "string",
                    "example": "duty-uuid"
                },
                "room_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000030001"
                },
                "room_number": {
                    "type": "string",
                    "example": "101"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                }
            }
        },
        "api.CleaningExemption": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "2026-08-07"
                },
                "id": {
                    "type": "string",
                    "example": "exemption-uuid"
                },
                "reason": {
                    "type": "string",
                    "example": "Ремонт"
                },
                "room_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000030001"
                },
                "start_date": {
                    "type": "string",
                    "example": "2026-08-01"
                }
            }
        },
        "api.CleaningExemptionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.CleaningExemption"
                    }
                }
            }
        },
        "api.CleaningPenalty": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "string",
                    "example": "penalty-uuid"
                },
                "reason": {
                    "type": "string",
                    "example": "Невыполнение дежурства"
                },
                "room_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000030001"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                }
            }
        },
        "api.CleaningPenaltyResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.CleaningPenalty"
                    }
                }
            }
        },
        "api.CleaningScheduleResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.CleaningDuty"
                    }
                }
            }
        },
        "api.DormitoryItem": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "ул. Лермонтова, д. 80"
                },
                "eis_dormitory_code": {
                    "type": "string",
                    "example": "EIS-BLD-8"
                },
                "id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000000001"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Общежитие №8"
                }
            }
        },
        "api.DormitoryListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.DormitoryItem"
                    }
                }
            }
        },
        "api.EmployeeDormitoriesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.EmployeeDormitory"
                    }
                }
            }
        },
        "api.EmployeeDormitory": {
            "type": "object",
            "properties": {
                "dormitory_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000000001"
                },
                "dormitory_name": {
                    "type": "string",
                    "example": "Общежитие №8"
                },
                "role": {
                    "type": "string",
                    "example": "commandant"
                }
            }
        },
        "api.EmployeeInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "eb008023-1c16-4d89-a9ef-aeea6b7be792"
                },
                "position": {
                    "type": "string",
                    "example": "Заведующий общежитием"
                },
                "primary_dormitory_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000000001"
                },
                "role": {
                    "type": "string",
                    "example": "commandant"
                },
                "user_id": {
                    "type": "string",
                    "example": "abc6efcd-487b-4b42-a30c-3dbb0a60cfdd"
                }
            }
        },
        "api.EmployeeInfoResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.EmployeeInfo"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 404
                },
                "error": {
                    "type": "string",
                    "example": "dormitory not found"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "api.FloorItem": {
            "type": "object",
            "properties": {
                "dormitory_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000000001"
                },
                "floor_number": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000010001"
                }
            }
        },
        "api.FloorListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.FloorItem"
                    }
                }
            }
        },
        "api.LaundryBooking": {
            "type": "object",
            "properties": {
                "booking_id": {
                    "type": "string",
                    "example": "booking-uuid"
                },
                "machine_number": {
                    "type": "string",
                    "example": "1"
                },
                "slot_date": {
                    "type": "string",
                    "example": "2026-08-06"
                },
                "slot_end": {
                    "type": "string",
                    "example": "11:00"
                },
                "slot_start": {
                    "type": "string",
                    "example": "10:00"
                }
            }
        },
        "api.LaundryBookingResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.LaundryBooking"
                }
            }
        },
        "api.LaundrySettingsItem": {
            "type": "object",
            "properties": {
                "booking_end_time": {
                    "type": "string",
                    "example": "23:00:00"
                },
                "booking_same_day_only": {
                    "type": "boolean",
                    "example": true
                },
                "booking_start_time": {
                    "type": "string",
                    "example": "07:00:00"
                },
                "default_duration_minutes": {
                    "type": "integer",
                    "example": 60
                },
                "dormitory_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000000001"
                },
                "id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000300001"
                }
            }
        },
        "api.LaundrySettingsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.LaundrySettingsItem"
                }
            }
        },
        "api.LaundrySlot": {
            "type": "object",
            "properties": {
                "machine_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000200001"
                },
                "machine_number": {
                    "type": "string",
                    "example": "1"
                },
                "slot_end": {
                    "type": "string",
                    "example": "08:00"
                },
                "slot_start": {
                    "type": "string",
                    "example": "07:00"
                }
            }
        },
        "api.LaundrySlotListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.LaundrySlot"
                    }
                }
            }
        },
        "api.MaterialItem": {
            "type": "object",
            "properties": {
                "condition": {
                    "type": "string",
                    "example": "хорошее"
                },
                "id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000040001"
                },
                "inventory_number": {
                    "type": "string",
                    "example": "MOCK-INV-101-001"
                },
                "item_name": {
                    "type": "string",
                    "example": "Кровать"
                },
                "quantity": {
                    "type": "integer",
                    "example": 3
                },
                "room_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000030001"
                }
            }
        },
        "api.MaterialItemListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.MaterialItem"
                    }
                }
            }
        },
        "api.MaterialItemResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.MaterialItem"
                }
            }
        },
        "api.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "booking cancelled"
                }
            }
        },
        "api.ReferenceMaterialItem": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "example": "Правила"
                },
                "description": {
                    "type": "string",
                    "example": "Правила внутреннего распорядка."
                },
                "dormitory_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000000001"
                },
                "id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000600001"
                },
                "name": {
                    "type": "string",
                    "example": "Правила проживания"
                },
                "ordinal": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "api.ReferenceMaterialListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ReferenceMaterialItem"
                    }
                }
            }
        },
        "api.ResidentDebt": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 1500
                },
                "description": {
                    "type": "string",
                    "example": "Задолженность за проживание"
                },
                "id": {
                    "type": "string",
                    "example": "debt-uuid"
                },
                "period": {
                    "type": "string",
                    "example": "2025-01"
                },
                "resident_id": {
                    "type": "string",
                    "example": "resident-uuid"
                }
            }
        },
        "api.ResidentDebtResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ResidentDebt"
                    }
                }
            }
        },
        "api.ResidentProfile": {
            "type": "object",
            "properties": {
                "contract_end": {
                    "type": "string",
                    "example": "2025-06-30"
                },
                "contract_num": {
                    "type": "string",
                    "example": "K-2024-001"
                },
                "contract_start": {
                    "type": "string",
                    "example": "2024-09-01"
                },
                "dormitory_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000000001"
                },
                "id": {
                    "type": "string",
                    "example": "resident-uuid"
                },
                "room_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000030001"
                },
                "user_id": {
                    "type": "string",
                    "example": "abc6efcd-487b-4b42-a30c-3dbb0a60cfdd"
                }
            }
        },
        "api.ResidentProfileResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.ResidentProfile"
                }
            }
        },
        "api.RoleItem": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string",
                    "example": "Заведующий"
                },
                "id": {
                    "type": "string",
                    "example": "r-commandant"
                },
                "is_system": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "commandant"
                },
                "priority": {
                    "type": "integer",
                    "example": 100
                },
                "target_type": {
                    "type": "string",
                    "example": "employee"
                }
            }
        },
        "api.RoleListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.RoleItem"
                    }
                }
            }
        },
        "api.RoomItem": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer",
                    "example": 3
                },
                "dormitory_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000000001"
                },
                "floor_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000010001"
                },
                "id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000030001"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "room_number": {
                    "type": "string",
                    "example": "101"
                }
            }
        },
        "api.RoomListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.RoomItem"
                    }
                }
            }
        },
        "api.RoomResidentItem": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string",
                    "example": "Артём"
                },
                "id": {
                    "type": "string",
                    "example": "resident-uuid"
                },
                "last_name": {
                    "type": "string",
                    "example": "Иванов"
                },
                "phone": {
                    "type": "string",
                    "example": "79001234501"
                },
                "room_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000030001"
                },
                "user_id": {
                    "type": "string",
                    "example": "abc6efcd-487b-4b42-a30c-3dbb0a60cfdd"
                }
            }
        },
        "api.RoomResidentsResponse": {
            "type": "object",
            "properties": {
                "residents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.RoomResidentItem"
                    }
                }
            }
        },
        "api.StaffItem": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string",
                    "example": "Заведующий"
                },
                "first_name": {
                    "type": "string",
                    "example": "Данил"
                },
                "last_name": {
                    "type": "string",
                    "example": "Высоких"
                },
                "phone": {
                    "type": "string",
                    "example": "79025643215"
                },
                "role": {
                    "type": "string",
                    "example": "commandant"
                },
                "user_id": {
                    "type": "string",
                    "example": "abc6efcd-487b-4b42-a30c-3dbb0a60cfdd"
                }
            }
        },
        "api.StaffListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.StaffItem"
                    }
                }
            }
        },
        "api.WashingMachineItem": {
            "type": "object",
            "properties": {
                "dormitory_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000000001"
                },
                "duration_minutes": {
                    "type": "integer",
                    "example": 60
                },
                "floor_id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000010001"
                },
                "id": {
                    "type": "string",
                    "example": "b0000000-0000-0000-0000-000000200001"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "machine_number": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "api.WashingMachineListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.WashingMachineItem"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Dormitory Bot API",
	Description:      "REST API for dormitory management mini-app (MAX Messenger).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
