package domain

var Models = []interface{}{
	&Role{},
	&User{},
	&Resident{},
	&Employee{},
	&EmployeeDormitoryRole{},
	&Dormitory{},
	&Floor{},
	&Wing{},
	&Room{},
	&WashingMachine{},
	&LaundryBooking{},
	&LaundrySlot{},
	&LaundrySettings{},
	&MaterialResponsibility{},
	&SanitaryControl{},
	&DisciplineControl{},
	&CohabitationControl{},
	&ResidentFinancialDebt{},
	&ReferenceMaterial{},
	&ChatLink{},
	&CleaningDuty{},
	&PenaltyCleaning{},
	&CleaningExemption{},
	&CleaningSettings{},
	&BotModule{},
}
